### PR TITLE
Port R bindings update to IM6 branch

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by jeroen** [comment]
Also ported one other PR fix.

**Comment by dlemstra** [comment]
Thanks! Did you check all of the other pull requests or do we still need to do that?

**Comment by jeroen** [comment]
I also checked https://github.com/ImageMagick/Website/pull/2/files but it was already applied.

**Comment by jeroen** [comment]
Also https://github.com/ImageMagick/Website/pull/3/files is already applied, so that is all of them.

**Pull request merged**
