### PR TITLE
Minor clarifications, explanations and consistency improvements.

### PR DESCRIPTION
**Pull request by MarkSetchell**

### CODE REVIEW

**Comment by dlemstra** [comment]
Could you do a rebase of your new changes instead of merging master?

p.s. Would you mind taking a look at the IM6 branch also?

**Comment by MarkSetchell** [comment]
Hi Dirk

Sorry, I don't understand, or know how/why to do a rebase.

Originally, I cloned your ImageMagick/Website repo on GitHub into my personal GitHub account and then cloned that onto my Mac. I then update stuff on my Mac and when I am happy with it, I commit it on my Mac and then I do "git push origin master" to update my GitHub account. Then I go to my personal GitHub account and create a "pull request" to you.

My remote settings in the repo on my Mac (from "git remote -v") are:

origin	git@github.com:MarkSetchell/Website.git (fetch)
origin	git@github.com:MarkSetchell/Website.git (push)
upstream	git@github.com:ImageMagick/Website.git (fetch)
upstream	git@github.com:ImageMagick/Website.git (push)

So, how would I do a rebase? And should I always do that in future, or just this one time?

Also, what did you want me to do in the IM6 branch exactly?

Sorry to be so dense!
Mark

**Comment by dlemstra** [comment]
No need to be sorry. We are here to help :) It looks like you are trying to push a couple commits from your previous pull request. These changes have been added to the repository by us with a rebase and that now makes it look like you are also trying to push the old changes. You could have avoided this by creating a separate branch for your changes. You can find some information on how to do that here: https://gist.github.com/Chaser324/ce0505fbed06b947d962. Would it be possible to do your last 3 commits from this pull request in a separate branch? We don't mind doing that ourselves if that would be more convenient for you.

The things that you have fixed are probably also incorrect in the ImageMagick-6 branch: https://github.com/ImageMagick/Website/tree/ImageMagick-6. We can apply your changes there if you prefer that.

**Comment by MarkSetchell** [comment]
Hi Dirk

Thank you for this. I am away in the Scottish Islands for a couple of weeks so I'll try and wirk out how better to contribute when I get back home with proper Internet!

Best regards
Mark

**Comment by dlemstra** [comment]
@MarkSetchell Can you take another look at this PR?

**Comment by MarkSetchell** [comment]
Hi Dirk,

I don't have time at the moment to get familiar enough with git to do what you ask - all the tutorials I read are confusing and launch into many acronyms and concepts that I am not familiar with and which they don't explain very well.

Feel free to ignore my changes and throw them away and I will maybe do them again in the way you suggest when I can get my head around git.

Also, I did not hear any more from the 2 guys who were willing to help update the "ImageMagick Usage pages" by Anthony Thyssen though I left them a message on GitHub to Email me?

Also, you have an Email address you can share with me please? I am at mark@thesetchells.com <mailto:mark@thesetchells.com>

Thanks
Mark

**Pull request closed without merging**
